# Generated by Django 5.1 on 2024-09-21 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_autor", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Temas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tema", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_publicacion", models.DateField()),
                ("editorial", models.CharField(max_length=200)),
                ("paginas", models.PositiveBigIntegerField()),
                ("esta_disponible", models.BooleanField(default=False)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=15)),
                ("link_referencia", models.URLField(max_length=300)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("autor", models.ManyToManyField(to="libros.autores")),
                ("nombreTema", models.ManyToManyField(to="libros.temas")),
            ],
        ),
    ]
