# Generated by Django 5.1 on 2024-09-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="fecha_publicacion",
        ),
        migrations.AddField(
            model_name="libro",
            name="año_publicacion",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
