# Generated by Django 5.1 on 2024-09-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0007_alter_libro_link_portada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="link_portada",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
