# Generated by Django 5.1 on 2024-09-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0008_alter_libro_link_portada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="año_publicacion",
        ),
        migrations.AlterField(
            model_name="libro",
            name="link_portada",
            field=models.URLField(default="https://www.example.com", max_length=300),
        ),
    ]
